workspace:
  base: /go
  path: src/github.com/gombio/hilda

pipeline:
  build:
    image: golang:latest
    commands:
      - go get ./...
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - dep ensure
      - go test
      - go build
