workspace:
  base: /go
  path: src/github.com/gombio/hilda

pipeline:
  build:
    image: golang:latest
    commands:
      - go get ./...
      - go get -u golang.org/x/lint/golint
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - dep ensure
      - go test `find . -type d -not -path "./vendor*" -not -path "./.git*"`
      - golint `find . -type d -not -path "./vendor*" -not -path "./.git*"
      - go vet `find . -type d -not -path "./vendor*" -not -path "./.git*"`
      - go build
